---
- name: Run swap.sh script on all hosts
  hosts: all
  become: yes
  tasks:
    - name: Download swap.sh script
      get_url:
        url: https://raw.githubusercontent.com/voutuk/file/main/swap.sh
        dest: /tmp/swap.sh
      get_url:
        url: https://raw.githubusercontent.com/voutuk/file/main/docker.sh
        dest: /tmp/docker.sh

    - name: Execute swap.sh script
      shell: sudo bash /tmp/swap.sh
      shell: sudo bash /tmp/docker.sh

- name: Create Docker Swarm and add nodes
  hosts: master
  become: yes
  tasks:
    - name: Initialize Docker Swarm
      command: docker swarm init
      register: swarm_init_result
      ignore_errors: yes

    - name: Save join token
      set_fact:
        join_token: "{{ swarm_init_result.stdout_lines[1] }}"
      when: swarm_init_result.rc == 0

- name: Add worker nodes to Swarm
  hosts: nodes
  become: yes
  tasks:
    - name: Join Swarm as worker
      command: "{{ hostvars['manager_node'].join_token }} {{ hostvars['manager_node'].ansible_host }}"